### ISSUE TITLE
Websites down - Where I can find logs?

### ISSUE THREAD

**Issue by tominovoj** [ail-project/lacus#17]
Hello,

I am starting with AIL as well as with its crawler Lacus. However I am getting all errors after requesting/crawling websites? Do you know where could be problem or where I can find application logs to get more info? Thanks in advanced!

![down_problem](https://github.com/ail-project/lacus/assets/116872706/9368f2ab-f72f-4a5a-b810-cdf52a882cb1)

**Comment by Rafiot** [comment]
Hello,

By default in lacus, if a website is down, a line will be printed in stdout by [capture_manager](https://github.com/ail-project/lacus/blob/main/bin/capture_manager.py), if you want to write the info-level logs to a file, you can configure it in [this file](https://github.com/ail-project/lacus/blob/main/config/logging.json.sample): rename it to `logging.json` and make it look something like that:

```
{
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
        "simple": {
            "format": "%(asctime)s %(name)s %(levelname)s:%(message)s"
        }
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "simple",
            "stream": "ext://sys.stdout"
        },
        "file_warning": {
            "class": "logging.handlers.RotatingFileHandler",
	    "level": "WARNING",
            "formatter": "simple",
            "filename": "logs/warning.log",
            "mode": "a",
            "maxBytes": 1000000,
            "backupCount": 5
        },
        "file_info": {
            "class": "logging.handlers.RotatingFileHandler",
	    "level": "INFO",
            "formatter": "simple",
            "filename": "logs/info.log",
            "mode": "a",
            "maxBytes": 1000000,
            "backupCount": 5
        }
    },
    "root": {
        "level": "DEBUG",
        "handlers": [
            "stdout",
            "file_warning",
            "file_info"
        ]
    }
}
```

**Comment by tominovoj** [comment]
Hello,

thank you. Now I see the logs, but problem is that all sended url's is showing like `DOWN` and I cannot crawl any on them.. I am getting following error:

```
2024-01-22 11:19:20,593 playwrightcapture ERROR:Something went poorly with https://www.bbc.co.uk/news: Target page, context or browser has been closed
Traceback (most recent call last):
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwrightcapture/capture.py", line 564, in capture_page
    await page.mouse.move(x=random.uniform(300, 800), y=random.uniform(200, 500))
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 1422, in move
    return mapping.from_maybe_impl(await self._impl_obj.move(x=x, y=y, steps=steps))
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_input.py", line 48, in move
    await self._channel.send("mouseMove", locals_to_params(locals()))
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
```

**Comment by Rafiot** [comment]
that's quite weird. What happen when you do `curl https://www.bbc.co.uk/news` from the same machine you have lacus running?

**Comment by tominovoj** [comment]
Hello,

sorry it was my bad and I resolved it.. However getting another error like that: Still not getting to work crawler..

```log
socmaster@circl-ail:~/lacus$ 2024-01-25 06:09:51,798 playwrightcapture ERROR:Something went poorly with http://lockbitapt2d73krlbewgv27tquljgxr33xbwwsp6rkyieto7u4ncead.onion: Target page, context or browser has been closed
Traceback (most recent call last):
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwrightcapture/capture.py", line 761, in _failsafe_get_content
    return await page.content()
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9158, in content
    return mapping.from_maybe_impl(await self._impl_obj.content())
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 458, in content
    return await self._main_frame.content()
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 410, in content
    return await self._channel.send("content")
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwrightcapture/capture.py", line 598, in capture_page
    if content := await self._failsafe_get_content(page):
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwrightcapture/capture.py", line 765, in _failsafe_get_content
    await page.wait_for_timeout(1000)
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 11738, in wait_for_timeout
    await self._impl_obj.wait_for_timeout(timeout=timeout)
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 938, in wait_for_timeout
    await self._main_frame.wait_for_timeout(timeout)
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 756, in wait_for_timeout
    await self._channel.send("waitForTimeout", locals_to_params(locals()))
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/home/socmaster/.cache/pypoetry/virtualenvs/lacus-l2MNtlLw-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
2024-01-25 06:09:53,210 LacusCore INFO:[9eae1496-d866-4611-a36c-5e0d5e485c24] Capture of http://lockbitapt2d73krlbewgv27tquljgxr33xbwwsp6rkyieto7u4ncead.onion finished - Runtime: 42.62714767456055s
```

**Comment by Rafiot** [comment]
This exception is caught and can happen, the browsers don't always finish cleanly. The very last line shows the capture finished.

Are other captures working? Or are they all failing?

**Comment by tominovoj** [comment]
They are all still failing, no clue why, internet connection works fine as well as tor socks5 proxy..

**Comment by Rafiot** [comment]
Yeah, I don't really understand either: we have multiple working lacus instances.

Without using AIL, if you connect to lacus on the web interface (by default: http://0.0.0.0:7100), and try to enqueue a capture like `google.com` can you check if it works?

**Comment by tominovoj** [comment]
Hello, this seems to work..

![response](https://github.com/ail-project/lacus/assets/116872706/f1977b4c-60d2-42c1-ba4b-d16819e399fa)

**Comment by Rafiot** [comment]
And now, try to get the result by passing the UUID to `capture_result` (and check the status in `capture_status`).

If that works, try to do the same with an onion domain.

**Comment by tominovoj** [comment]
I am getting `capture_status` equal to `0` both for onion as well as normal website.

**Comment by Rafiot** [comment]
ok, so queued but not captured. Is the `capture_manager` script running?

**Comment by tominovoj** [comment]
yes its running.

**Comment by tominovoj** [comment]
It seems that request for crawler are stucking in Queue. I have no specific logs about maybe just following (not sure if they are helpfull)

```log
2024-01-25 10:25:45,896 CaptureManager INFO:Max amount of captures in parallel reached (2)
2024-01-25 10:25:45,974 LacusCore INFO:[ee3bff1e-446e-4a8b-a737-4859ca8f794a] Capture of https://www.bbc.co.uk/ finished - Runtime: 36.088971853256226s
2024-01-25 11:07:15,620 LacusCore INFO:[15bde2b4-1350-431f-9dda-945c2bba3759] Capture of https://www.bbc.com/ finished - Runtime: 50.714940547943115s
2024-01-25 11:07:51,621 CaptureManager WARNING:3e20bdc4-efec-417f-a4e0-fe1f78014fe4 has been running for too long. Started at 2024-01-25 10:02:51.412930.
```

**Comment by Rafiot** [comment]
You only allow two captures in parallel, it is not necessarily a problem but that could explain why the captures you just added were not started (yet). I also see that captures with UUIDs `ee3bff1e-446e-4a8b-a737-4859ca8f794a` and `15bde2b4-1350-431f-9dda-945c2bba3759` finished, so you can pass them to `capture_result` and you should get something.

I've been adding a few more monitoring features in lacus in the last few days, so you can run `poetry run python tools/monitoring.py` and have a bit of an idea of the status of the queue. If you have a lot of entries int here, the last ones you added may take a very long time too be be processed.

**Comment by tominovoj** [comment]
Nice, that's great idea!

- `15bde2b4-1350-431f-9dda-945c2bba3759` -> passed nice - I have full response. However in AIL is status still `DOWN` (sending also print screen)

Here is my response from the `monitoring.py` tool:

```log
Services currently running:
Got a dead script: capture_manager - 26139
Got a dead script: capture_manager - 27535
Got a dead script: capture_manager - 27765
Got a dead script: capture_manager - 45707
Got a dead script: capture_manager - 1091
Got a dead script: capture_manager - 47650
Got a dead script: capture_manager - 26159
Got a dead script: capture_manager - 1874
Got a dead script: capture_manager - 1032
Got a dead script: website - 45706
Got a dead script: website - 47649
  capture_manager (2 service(s))                                                                     
  website (2 service(s))                                                                             
DB info:
  21 keys in the database.                                                                           
  Current memory use: 6.20M                                                                          
  Peak memory use: 8.85M                                                                             
Daily stats:
  7 captures                                                                                         
  Errors:                                                                                            
    TargetClosedError: 1                                                                             
Ongoing captures:
  3e20bdc4-efec-417f-a4e0-fe1f78014fe4: 2024-01-25 10:02:51.412930                                   
    {                                                                                                
      "url": "http://lockbitapt2d73krlbewgv27tquljgxr33xbwwsp6rkyieto7u4ncead.onion/",               
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0",          
      "proxy": "force_tor",                                                                          
      "depth": "0",                                                                                  
      "rendered_hostname_only": "1",                                                                 
      "general_timeout_in_sec": "90"                                                                 
    }                                                                                                
Enqueued captures:
  fd87da7d-48e8-46e1-b342-da7902a050c8: 0.0                                                          
  d3edbd0f-d831-47b7-b5b0-f831a1edd615: 0.0                                                          
  0c3eaf5a-e0e8-4017-be9e-47d386e81675: -5.0                                                         
  0bfa2844-6670-49eb-8a4a-87233e0ccbc2: -5.0 
```


![bbc_response](https://github.com/ail-project/lacus/assets/116872706/46ec800c-3238-4c51-8021-7f6e6c8e944d)

**Comment by Rafiot** [comment]
Regarding AIL seeing it as down, I'm going to invoke @Terrtia because I'm not sure why nor what to look for. Could it be because for some reason it takes too long and AIL doesn't wait long enough for the capture to be done before deciding it is down?

You have one onion capture ongoing. It should be done by now, can you check if the result for `3e20bdc4-efec-417f-a4e0-fe1f78014fe4` is present?

**Comment by tominovoj** [comment]
Oh thanks, its weird that in `Lacus` I can clearly see response.. Maybe It would be benefical to find `AIL` logs. Where are place for AIL logs? 

Anyway, Status of the onion site  `3e20bdc4-efec-417f-a4e0-fe1f78014fe4` is `2`, which should be probably still `ongoing`. This scan has started at  2024/01/25 - 10:02.50. 

![onion](https://github.com/ail-project/lacus/assets/116872706/2524429a-bf6d-4ec1-9211-499d738881d7)

**Comment by Rafiot** [comment]
some captures can take a very long time on AIL as it will attempt to fetch every links on the lading page

**Comment by tominovoj** [comment]
Thanks for now, because it seems great project (thanks for it!), but crawler its important for all of it.. By the way is there any Discord community channel or just GItter channel? And also is there some guide how to configure things like in AIL or just training materials and github readme's? Thanks!

**Comment by Rafiot** [comment]
No, we do not have a Discord nor gitter channel, they are hard to keep track of. And well, documentation wise, that's mostly the readme.

For Lacus, you can increase the number of captures allowed to take place in parallel (that will probably make things better) by changing the value in the config file.

**Comment by Terrtia** [comment]
Hello!
AIL logs are located in ``ail-framework/logs/crawler.log``.

By default, AIL is using the Lacus API and setting the "general_timeout_in_sec" for each capture to 90 seconds.
It considers a domain down if the first URL takes more than 90 seconds.

Are you using the Tor proxy by default? 
Can you manually retry by setting the "Crawler Type" to web ?

**Comment by tominovoj** [comment]
Hello,

thanks for all help - I have upgrade system resources as well number of parallel tasks in Lacus and now its working. Thanks! This issue can be closed.

**Comment by Rafiot** [comment]
nice, thank you for the update!
